[package]
name = "gruvbox_converter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = { version = "0.24"}
palette = "0.7"
rand = "0.8"
imageproc = "0.23"